networks:
  prod:
    driver: bridge

services:
  db:
    image: postgres:17-alpine
    restart: unless-stopped
    shm_size: 256mb
    environment:
      - POSTGRES_USER=umir_user
      - POSTGRES_PASSWORD=0607078219
      - POSTGRES_DB=umir_db

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U umir_user -d umir_db"] #сначала юзер, потом название БД
      interval: 10s
      timeout: 30s
      retries: 5

    ports:
      - 5432:5432

    networks:
      - prod

  adminer:
    image: adminer
    container_name: adm_hack
    restart: always
    ports:
      - 7000:8080
    networks:
      - prod

volumes:
  postgres_data:
